apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jitsi-config
  namespace: jitsi
spec:
  encryptedData:
    secrets: AgCLM1vbn15Q0LRViDGAp+VZpkrFmSW1ToGkecnqItzk7jDkBkjksUNSoNH+gj2pcCC4XygpXr5YylX/CWi+IEwBAgdswvcpTAFyhkZGt1Xsw2NR+7kWaHPUpPIna2Q+4A8SJkl2m6Pmzcwd8wymxnPbkW7XjXrWxnXbsSDNa3HD42AM9ZMxkayrTC/78p5gCNOFFZqiUP0ItIGSp5jIlr6xMOkvBc8SPK0pTrUFfqeIfz4V5+34tZa5Y71ENwEEn6fIslo1ha4a9ujTBqhV3+kd7UKNYBx6eA2mO2qP+ZddfzEBzyq04NhbEwP0Ck84ambxPha/Zt+QxQqQRCF/cR0C2/GtIQ2I7Nz6glD2dXQcWMv580YlvGIcGo6hPKX1Q/wEQxbO2R1hXy2lYC6egqo0OvAr3GFvFx0RrcAafVhFJxvWA1i0bgF7R/mrSNdxKqZRjKjv9keYz20J+2xiKgolty8a9LsEEr5QEBbksWBttswtq+X3Ue5fZaWuSOqZgqtDntIWok6EM4Rm6niZ7cu3LYNi6H2yxricpd7p1iHbHFEWtFHMS3Xz441s7d2BO4cj8hHhya0R7WFOOgKNf8KgWLG3L0nTiQ70J/+nhiJH1xHQsADknNdQaVq7luFdq/DDQx4RNhaWCcguffSBXRPhZLpYVTs+WFavjzPuT4Jx/FYmlgoNeJw3wgsvbfXX8XkxXqx7Ze8stCWNgdhJSP6C8OGlX1AWAUSkB4VU9+zlZsripV6BNQXw606WIPZKkVMIDnlzCrzEARKZ26iguVac+MES4jgELE3uUa+p/u+8KACNdFYpLwpaFel+s4rsF23/WeRVDgKSErpKkLgxCs9SKRqkFZ0=
  template:
    metadata:
      creationTimestamp: null
      name: jitsi-config
      namespace: jitsi
